language: c

matrix:
    include:
        - env: test="Original"

          os: linux
          dist: trusty
          compiler: gcc
          script: ./autogen.sh && ./configure && make && make check && make distcheck
          before_script: 
            - ./.travis/install-gettext.sh
            - ./.travis/install-automake.sh
            - export PATH=$HOME/bin:$PATH

        - env: test="x64 4.8.4 (CMake gcc)"
          os: linux
          dist: trusty
          compiler: gcc
          before_script:
              - mkdir gcc_rel && cd gcc_rel
              - cmake ..
          script:  make

        - env: test="x64 (CMake clang)"
          os: linux
          dist: trusty
          compiler: clang
          before_script:
              - mkdir clang_rel && cd clang_rel
              - cmake ..
          script:  make

        - env: test="x64 (CMake clang - Ninja) Debug"
          os: linux
          dist: trusty
          compiler: clang
          before_script:
              - mkdir clang_ninja_dbg && cd clang_ninja_dbg
              - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug
          script:  ninja

        - env: test="x64 (CMake clang - Ninja) Install / Uninstall"
          os: linux
          dist: trusty
          compiler: clang
          before_script:
              - mkdir clang_ninja && cd clang_ninja
              - cmake .. -GNinja -DCMAKE_INSTALL_PREFIX=./out
          script:
              - ninja install
              - ninja uninstall

addons:

    apt:
        packages:
            - autoconf
            - bison
            - gcc-6
            - help2man
            - lzip
            - texinfo
            - texlive
            - automake
            - libtool
            - m4
            - cmake
            - ninja-build
        sources:
            - ubuntu-toolchain-r-test
